"""
Django settings for proyecto project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Define el directorio base del proyecto.
BASE_DIR = Path(__file__).resolve().parent.parent


# Clave secreta para la seguridad criptográfica de Django. ¡No compartir en producción!
SECRET_KEY = 'django-insecure-**053x^ma+*(q0&ia&s^%hgw#c603@^^udr!j4_8r=0ud^p)8r'

# El modo DEBUG muestra errores detallados. Debe ser False en un entorno de producción.
DEBUG = True

ALLOWED_HOSTS = []


# --- Definición de Aplicaciones ---
# Aquí se listan todas las aplicaciones que componen el proyecto Django.
INSTALLED_APPS = [
    # Aplicaciones por defecto de Django:
    'django.contrib.admin',      # El panel de administración.
    'django.contrib.auth',       # El framework de autenticación.
    'django.contrib.contenttypes', # Framework para tipos de contenido.
    'django.contrib.sessions',     # El framework de sesiones.
    'django.contrib.messages',     # El framework de mensajería.
    'django.contrib.staticfiles',  # Framework para gestionar archivos estáticos (CSS, JS, imágenes).

    # Aplicaciones del proyecto:
    'base.apps.BaseConfig',  # Se registra la aplicación 'base' que hemos creado.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Define el archivo principal de configuración de URLs para el proyecto.
ROOT_URLCONF = 'proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,  # Hace que Django busque plantillas dentro de los directorios 'templates' de cada aplicación.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto.wsgi.application'


# --- Configuración de la Base de Datos ---
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    # Por defecto, se usa SQLite, que es una base de datos ligera basada en un solo archivo.
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # El archivo de la base de datos se creará en el directorio raíz del proyecto.
    }
}


# Validadores de contraseñas.
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Internacionalización ---
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_URL = 'login'

# --- Archivos Estáticos (CSS, JavaScript, Imágenes) ---
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'

# Tipo de campo de clave primaria por defecto.
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# URL a la que se redirige después de un inicio de sesión exitoso.
LOGIN_REDIRECT_URL = '/'
